export const SET_CURRENCY_CODE = 'SET_CURRENCY_CODE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';

export const CREATE_SCHEDULE_EXCEPTION = 'CREATE_SCHEDULE_EXCEPTION';

export const FETCH_OCCURRENCES = 'FETCH_OCCURRENCES';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';

export const SET_STARTING_BALANCE = 'SET_STARTING_BALANCE';