export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';

export const FETCH_OCCURRENCES = 'FETCH_OCCURRENCES';

export const SET_STARTING_BALANCE = 'SET_STARTING_BALANCE';